import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import clsx from 'clsx'
import './globals.css'

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], variable: '--font-noto-sans-jp' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${clsx(notoSansJP.variable, 'font-sans')} bg-slate-50`}>{children}</body>
    </html>
  )
}
